name: Publish Development Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            persist-credentials: false

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Clean Gradle cache
        run: ./gradlew clean build --refresh-dependencies

      - name: Build with Gradle
        run: ./gradlew build

      - name: Extract Minecraft Version from fabric.mod.json
        id: extract_version
        run: |
          mc_version=$(jq -r '.depends.minecraft[0]' src/main/resources/fabric.mod.json)
          echo "Minecraft Version is $mc_version"
          echo "MC_VERSION=$mc_version" >> $GITHUB_ENV

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: ${{ env.MC_VERSION }}
          prerelease: true
          title: Dev Build
          files: |
            ./build/libs/*.jar
